_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 4/5 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # merge 4: vehicle+human+ground+nature
                m4_vhgn=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 20, 21, 22],  # vehicle+human+ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 4: vehicle+human+ground+object
                m4_vhgo=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+human+ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 4: vehicle+human+construction+nature
                m4_vhcn=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+human+construction+nature
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # merge 4: vehicle+human+construction+object
                m4_vhco=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+human+construction+object
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # merge 4: vehicle+human+nature+object
                m4_vhno=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+nature+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 4: vehicle+ground+construction+nature
                m4_vgcn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+ground+construction+nature
                    [5, 6],  # human
                    [7, 8, 18, 23],  # object
                ],
                # merge 4: vehicle+ground+construction+object
                m4_vgco=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+ground+construction+object
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                ],
                # merge 4: vehicle+ground+nature+object
                m4_vgno=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # vehicle+ground+nature+object
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 4: vehicle+construction+nature+object
                m4_vcno=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+construction+nature+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                ],
                # merge 4: human+ground+construction+nature
                m4_hgcn=[
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+ground+construction+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [7, 8, 18, 23],  # object
                ],
                # merge 4: human+ground+construction+object
                m4_hgco=[
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+ground+construction+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [20, 21, 22],  # nature
                ],
                # merge 4: human+ground+nature+object
                m4_hgno=[
                    [5, 6, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # human+ground+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
