_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 3/5 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # merge 3: vehicle+nature+object
                m3_vno=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 3: human+ground+construction
                m3_hgc=[
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                    [0, 1, 2, 3, 4],  # vehicle
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: human+ground+nature
                m3_hgn=[
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: human+ground+object
                m3_hgo=[
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 3: human+construction+nature
                m3_hcn=[
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: human+construction+object
                m3_hco=[
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # merge 3: human+nature+object
                m3_hno=[
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 3: ground+construction+nature
                m3_gcn=[
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: ground+construction+object
                m3_gco=[
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                ],
                # merge 3: ground+nature+object
                m3_gno=[
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 3: construction+nature+object
                m3_cno=[
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                ],
                # merge 4: vehicle+human+ground+construction
                m4_vhgc=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+human+ground+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
