"""What the data/dso/*.pkl info files are.

They hold NO point data — just an index of the dataset, one dict per frame:

    {'metainfo': {'DATASET': 'DSO'},
     'data_list': [{
         'lidar_points': {'lidar_path': 'annotations/<seq>/<frame>.ply',
                          'num_pts_feats': 4},
         'pts_panoptic_mask_path': 'annotations/<seq>/<frame>.ply',  # same file:
         'sample_id': '<seq>/<frame-stem>',   # DSO PLYs hold points AND labels
     }, ...]}

Paths are relative to data_root ('data/dso/', where 'annotations' symlinks
Annotation_Final). At runtime Seg3DDataset joins them and the DSO loader reads
each PLY once for points + panoptic labels. Generated by
`python tools/create_data.py dso ...` (fixed splits, see dso_converter.py).

Run:  python3 trash/explain_dso_pkls.py
"""
import os
import pickle
from collections import Counter

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    'data', 'dso')

totals = {}
for split in ('train', 'val', 'test', 'mini'):
    path = os.path.join(ROOT, f'dso_infos_{split}.pkl')
    with open(path, 'rb') as fh:
        infos = pickle.load(fh)
    frames = infos['data_list']
    seqs = Counter(e['sample_id'].split('/')[0] for e in frames)
    print(f'=== dso_infos_{split}.pkl  ({len(frames)} frames, '
          f'{os.path.getsize(path) / 1e6:.1f} MB, metainfo={infos["metainfo"]})')
    for seq, n in seqs.items():
        print(f'    {n:5d}  {seq}')
    e = frames[0]
    print(f'    example entry: {e}')
    full = os.path.join(ROOT, e['lidar_points']['lidar_path'])
    print(f'    resolved path exists: {os.path.isfile(full)}\n')
    totals[split] = len(frames)

n_all = totals['train'] + totals['val'] + totals['test']
print(f'TOTAL lidar frames: {n_all}  '
      f"(train {totals['train']} + val {totals['val']} + test {totals['test']}; "
      f"mini's {totals['mini']} excluded — it is a subset of train)")
