_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 13/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 4 groups: v | ho | gc | n
                p_v_ho_gc_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | ho | gn | c
                p_v_ho_gn_c=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: vc | h | g | no
                p_vc_h_g_no=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: vc | h | gn | o
                p_vc_h_gn_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vc | h | go | n
                p_vc_h_go_n=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vc | hg | n | o
                p_vc_hg_n_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vc | hn | g | o
                p_vc_hn_g_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vc | ho | g | n
                p_vc_ho_g_n=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vcn | h | g | o
                p_vcn_h_g_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vco | h | g | n
                p_vco_h_g_n=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vg | h | c | no
                p_vg_h_c_no=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: vg | h | cn | o
                p_vg_h_cn_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [7, 8, 18, 23],  # object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
