_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 7/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vgn | h | co
                p_vgn_h_co=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 3 groups: vgn | hc | o
                p_vgn_hc_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vgn | ho | c
                p_vgn_ho_c=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vgno | h | c
                p_vgno_h_c=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # vehicle+ground+nature+object
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vgo | h | cn
                p_vgo_h_cn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: vgo | hc | n
                p_vgo_hc_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vgo | hn | c
                p_vgo_hn_c=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6, 20, 21, 22],  # human+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vh | g | cno
                p_vh_g_cno=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                ],
                # 3 groups: vh | gc | no
                p_vh_gc_no=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: vh | gcn | o
                p_vh_gcn_o=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vh | gco | n
                p_vh_gco_n=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vh | gn | co
                p_vh_gn_co=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
