_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 14/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 4 groups: vg | h | co | n
                p_vg_h_co_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vg | hc | n | o
                p_vg_hc_n_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vg | hn | c | o
                p_vg_hn_c_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 20, 21, 22],  # human+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vg | ho | c | n
                p_vg_ho_c_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vgc | h | n | o
                p_vgc_h_n_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vgn | h | c | o
                p_vgn_h_c_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vgo | h | c | n
                p_vgo_h_c_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vh | g | c | no
                p_vh_g_c_no=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: vh | g | cn | o
                p_vh_g_cn_o=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vh | g | co | n
                p_vh_g_co_n=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vh | gc | n | o
                p_vh_gc_n_o=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vh | gn | c | o
                p_vh_gn_c_o=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
