_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 2/5 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # merge 2: construction+nature
                m2_cn=[
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: construction+object
                m2_co=[
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # merge 2: nature+object
                m2_no=[
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 3: vehicle+human+ground
                m3_vhg=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+human+construction
                m3_vhc=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+human+nature
                m3_vhn=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+human+object
                m3_vho=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 3: vehicle+ground+construction
                m3_vgc=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+ground+nature
                m3_vgn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+ground+object
                m3_vgo=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 3: vehicle+construction+nature
                m3_vcn=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # merge 3: vehicle+construction+object
                m3_vco=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
