_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 12/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 4 groups: v | hco | g | n
                p_v_hco_g_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | hg | c | no
                p_v_hg_c_no=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: v | hg | cn | o
                p_v_hg_cn_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | hg | co | n
                p_v_hg_co_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | hgc | n | o
                p_v_hgc_n_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | hgn | c | o
                p_v_hgn_c_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | hgo | c | n
                p_v_hgo_c_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | hn | g | co
                p_v_hn_g_co=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 4 groups: v | hn | gc | o
                p_v_hn_gc_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | hn | go | c
                p_v_hn_go_c=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: v | hno | g | c
                p_v_hno_g_c=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: v | ho | g | cn
                p_v_ho_g_cn=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
