_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 8/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vh | gno | c
                p_vh_gno_c=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vh | go | cn
                p_vh_go_cn=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: vhc | g | no
                p_vhc_g_no=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: vhc | gn | o
                p_vhc_gn_o=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vhc | go | n
                p_vhc_go_n=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vhcn | g | o
                p_vhcn_g_o=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+human+construction+nature
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vhco | g | n
                p_vhco_g_n=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+human+construction+object
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vhg | c | no
                p_vhg_c_no=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: vhg | cn | o
                p_vhg_cn_o=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vhg | co | n
                p_vhg_co_n=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vhgc | n | o
                p_vhgc_n_o=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+human+ground+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vhgn | c | o
                p_vhgn_c_o=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 20, 21, 22],  # vehicle+human+ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
