_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 6/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vg | h | cno
                p_vg_h_cno=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                ],
                # 3 groups: vg | hc | no
                p_vg_hc_no=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: vg | hcn | o
                p_vg_hcn_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vg | hco | n
                p_vg_hco_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vg | hn | co
                p_vg_hn_co=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 20, 21, 22],  # human+nature
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 3 groups: vg | hno | c
                p_vg_hno_c=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vg | ho | cn
                p_vg_ho_cn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: vgc | h | no
                p_vgc_h_no=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6],  # human
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: vgc | hn | o
                p_vgc_hn_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6, 20, 21, 22],  # human+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vgc | ho | n
                p_vgc_ho_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vgcn | h | o
                p_vgcn_h_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+ground+construction+nature
                    [5, 6],  # human
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vgco | h | n
                p_vgco_h_n=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+ground+construction+object
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
