_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 1/5 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # merge 2: vehicle+human
                m2_vh=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: vehicle+ground
                m2_vg=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: vehicle+construction
                m2_vc=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: vehicle+nature
                m2_vn=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: vehicle+object
                m2_vo=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 2: human+ground
                m2_hg=[
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [0, 1, 2, 3, 4],  # vehicle
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: human+construction
                m2_hc=[
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: human+nature
                m2_hn=[
                    [5, 6, 20, 21, 22],  # human+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: human+object
                m2_ho=[
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # merge 2: ground+construction
                m2_gc=[
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: ground+nature
                m2_gn=[
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # merge 2: ground+object
                m2_go=[
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
