_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 2/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 2 groups: vgo | hcn
                p_vgo_hcn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+ground+object
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                ],
                # 2 groups: vh | gcno
                p_vh_gcno=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # ground+construction+nature+object
                ],
                # 2 groups: vhc | gno
                p_vhc_gno=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                ],
                # 2 groups: vhcn | go
                p_vhcn_go=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+human+construction+nature
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                ],
                # 2 groups: vhcno | g
                p_vhcno_g=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+construction+nature+object
                    [9, 10, 11, 19],  # ground
                ],
                # 2 groups: vhco | gn
                p_vhco_gn=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+human+construction+object
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                ],
                # 2 groups: vhg | cno
                p_vhg_cno=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                ],
                # 2 groups: vhgc | no
                p_vhgc_no=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+human+ground+construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 2 groups: vhgcn | o
                p_vhgcn_o=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+human+ground+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 2 groups: vhgco | n
                p_vhgco_n=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+human+ground+construction+object
                    [20, 21, 22],  # nature
                ],
                # 2 groups: vhgn | co
                p_vhgn_co=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 20, 21, 22],  # vehicle+human+ground+nature
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 2 groups: vhgno | c
                p_vhgno_c=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+ground+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
