_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 5/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vc | hgn | o
                p_vc_hgn_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vc | hgo | n
                p_vc_hgo_n=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vc | hn | go
                p_vc_hn_go=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                ],
                # 3 groups: vc | hno | g
                p_vc_hno_g=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vc | ho | gn
                p_vc_ho_gn=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                ],
                # 3 groups: vcn | h | go
                p_vcn_h_go=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6],  # human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                ],
                # 3 groups: vcn | hg | o
                p_vcn_hg_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vcn | ho | g
                p_vcn_ho_g=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vcno | h | g
                p_vcno_h_g=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+construction+nature+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vco | h | gn
                p_vco_h_gn=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                ],
                # 3 groups: vco | hg | n
                p_vco_hg_n=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vco | hn | g
                p_vco_hn_g=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19],  # ground
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
