_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 1/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 2 groups: v | hgcno
                p_v_hgcno=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # human+ground+construction+nature+object
                ],
                # 2 groups: vc | hgno
                p_vc_hgno=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # human+ground+nature+object
                ],
                # 2 groups: vcn | hgo
                p_vcn_hgo=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+construction+nature
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                ],
                # 2 groups: vcno | hg
                p_vcno_hg=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+construction+nature+object
                    [5, 6, 9, 10, 11, 19],  # human+ground
                ],
                # 2 groups: vco | hgn
                p_vco_hgn=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+construction+object
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                ],
                # 2 groups: vg | hcno
                p_vg_hcno=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # human+construction+nature+object
                ],
                # 2 groups: vgc | hno
                p_vgc_hno=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # vehicle+ground+construction
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                ],
                # 2 groups: vgcn | ho
                p_vgcn_ho=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+ground+construction+nature
                    [5, 6, 7, 8, 18, 23],  # human+object
                ],
                # 2 groups: vgcno | h
                p_vgcno_h=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+ground+construction+nature+object
                    [5, 6],  # human
                ],
                # 2 groups: vgco | hn
                p_vgco_hn=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+ground+construction+object
                    [5, 6, 20, 21, 22],  # human+nature
                ],
                # 2 groups: vgn | hco
                p_vgn_hco=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22],  # vehicle+ground+nature
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                ],
                # 2 groups: vgno | hc
                p_vgno_hc=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # vehicle+ground+nature+object
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
