_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 17/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 5 groups: v | hc | g | n | o
                p_v_hc_g_n_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | hg | c | n | o
                p_v_hg_c_n_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | hn | g | c | o
                p_v_hn_g_c_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | ho | g | c | n
                p_v_ho_g_c_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 5 groups: vc | h | g | n | o
                p_vc_h_g_n_o=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: vg | h | c | n | o
                p_vg_h_c_n_o=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19],  # vehicle+ground
                    [5, 6],  # human
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: vh | g | c | n | o
                p_vh_g_c_n_o=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: vn | h | g | c | o
                p_vn_h_g_c_o=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: vo | h | g | c | n
                p_vo_h_g_c_n=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 6 groups: v | h | g | c | n | o (= current hierarchy)
                p_v_h_g_c_n_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # split each group in half
                sp=[
                    [2, 3],  # vehicle-a
                    [0, 1, 4],  # vehicle-b
                    [6],  # human-a
                    [5],  # human-b
                    [9, 11],  # ground-a
                    [10, 19],  # ground-b
                    [13, 16, 17],  # construction-a
                    [12, 14, 15],  # construction-b
                    [20],  # nature-a
                    [21, 22],  # nature-b
                    [7, 8],  # object-a
                    [18, 23],  # object-b
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
