_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 10/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vn | hgc | o
                p_vn_hgc_o=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vn | hgo | c
                p_vn_hgo_c=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vn | ho | gc
                p_vn_ho_gc=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                ],
                # 3 groups: vno | h | gc
                p_vno_h_gc=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                ],
                # 3 groups: vno | hc | g
                p_vno_hc_g=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vno | hg | c
                p_vno_hg_c=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vo | h | gcn
                p_vo_h_gcn=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                ],
                # 3 groups: vo | hc | gn
                p_vo_hc_gn=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                ],
                # 3 groups: vo | hcn | g
                p_vo_hcn_g=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vo | hg | cn
                p_vo_hg_cn=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: vo | hgc | n
                p_vo_hgc_n=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vo | hgn | c
                p_vo_hgn_c=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
