_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 5/5 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # merge 4: human+construction+nature+object
                m4_hcno=[
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # human+construction+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [9, 10, 11, 19],  # ground
                ],
                # merge 4: ground+construction+nature+object
                m4_gcno=[
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # ground+construction+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                ],
                # merge 5: vehicle+human+ground+construction+nature
                m5_vhgcn=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # vehicle+human+ground+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # merge 5: vehicle+human+ground+construction+object
                m5_vhgco=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # vehicle+human+ground+construction+object
                    [20, 21, 22],  # nature
                ],
                # merge 5: vehicle+human+ground+nature+object
                m5_vhgno=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+ground+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # merge 5: vehicle+human+construction+nature+object
                m5_vhcno=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+construction+nature+object
                    [9, 10, 11, 19],  # ground
                ],
                # merge 5: vehicle+ground+construction+nature+object
                m5_vgcno=[
                    [0, 1, 2, 3, 4, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # vehicle+ground+construction+nature+object
                    [5, 6],  # human
                ],
                # merge 5: human+ground+construction+nature+object
                m5_hgcno=[
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # human+ground+construction+nature+object
                    [0, 1, 2, 3, 4],  # vehicle
                ],
                # split each group in half
                sp=[
                    [2, 3],  # vehicle-a
                    [0, 1, 4],  # vehicle-b
                    [6],  # human-a
                    [5],  # human-b
                    [9, 11],  # ground-a
                    [10, 19],  # ground-b
                    [13, 16, 17],  # construction-a
                    [12, 14, 15],  # construction-b
                    [20],  # nature-a
                    [21, 22],  # nature-b
                    [7, 8],  # object-a
                    [18, 23],  # object-b
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
