_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 4/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: v | hg | cno
                p_v_hg_cno=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                ],
                # 3 groups: v | hgc | no
                p_v_hgc_no=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 3 groups: v | hgcn | o
                p_v_hgcn_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+ground+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: v | hgco | n
                p_v_hgco_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+ground+construction+object
                    [20, 21, 22],  # nature
                ],
                # 3 groups: v | hgn | co
                p_v_hgn_co=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 20, 21, 22],  # human+ground+nature
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 3 groups: v | hgno | c
                p_v_hgno_c=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # human+ground+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: v | hgo | cn
                p_v_hgo_cn=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # human+ground+object
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: v | hn | gco
                p_v_hn_gco=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                ],
                # 3 groups: v | hno | gc
                p_v_hno_gc=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 20, 21, 22, 7, 8, 18, 23],  # human+nature+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                ],
                # 3 groups: v | ho | gcn
                p_v_ho_gcn=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                ],
                # 3 groups: vc | h | gno
                p_vc_h_gno=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                ],
                # 3 groups: vc | hg | no
                p_vc_hg_no=[
                    [0, 1, 2, 3, 4, 12, 13, 14, 15, 16, 17],  # vehicle+construction
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
