_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 15/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 4 groups: vh | go | c | n
                p_vh_go_c_n=[
                    [0, 1, 2, 3, 4, 5, 6],  # vehicle+human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vhc | g | n | o
                p_vhc_g_n_o=[
                    [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17],  # vehicle+human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vhg | c | n | o
                p_vhg_c_n_o=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19],  # vehicle+human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vhn | g | c | o
                p_vhn_g_c_o=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vho | g | c | n
                p_vho_g_c_n=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vn | h | g | co
                p_vn_h_g_co=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 4 groups: vn | h | gc | o
                p_vn_h_gc_o=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vn | h | go | c
                p_vn_h_go_c=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: vn | hc | g | o
                p_vn_hc_g_o=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vn | hg | c | o
                p_vn_hg_c_o=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: vn | ho | g | c
                p_vn_ho_g_c=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 7, 8, 18, 23],  # human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: vno | h | g | c
                p_vno_h_g_c=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
