_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 9/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vhgo | c | n
                p_vhgo_c_n=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+human+ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vhn | g | co
                p_vhn_g_co=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 3 groups: vhn | gc | o
                p_vhn_gc_o=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [7, 8, 18, 23],  # object
                ],
                # 3 groups: vhn | go | c
                p_vhn_go_c=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vhno | g | c
                p_vhno_g_c=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+nature+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vho | g | cn
                p_vho_g_cn=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 3 groups: vho | gc | n
                p_vho_gc_n=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22],  # nature
                ],
                # 3 groups: vho | gn | c
                p_vho_gn_c=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 3 groups: vn | h | gco
                p_vn_h_gco=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                ],
                # 3 groups: vn | hc | go
                p_vn_hc_go=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                ],
                # 3 groups: vn | hco | g
                p_vn_hco_g=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: vn | hg | co
                p_vn_hg_co=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
