_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 11/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 3 groups: vo | hn | gc
                p_vo_hn_gc=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                ],
                # 4 groups: v | h | g | cno
                p_v_h_g_cno=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # construction+nature+object
                ],
                # 4 groups: v | h | gc | no
                p_v_h_gc_no=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: v | h | gcn | o
                p_v_h_gcn_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | h | gco | n
                p_v_h_gco_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | h | gn | co
                p_v_h_gn_co=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                ],
                # 4 groups: v | h | gno | c
                p_v_h_gno_c=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: v | h | go | cn
                p_v_h_go_cn=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 4 groups: v | hc | g | no
                p_v_hc_g_no=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 4 groups: v | hc | gn | o
                p_v_hc_gn_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [7, 8, 18, 23],  # object
                ],
                # 4 groups: v | hc | go | n
                p_v_hc_go_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [20, 21, 22],  # nature
                ],
                # 4 groups: v | hcn | g | o
                p_v_hcn_g_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                    [9, 10, 11, 19],  # ground
                    [7, 8, 18, 23],  # object
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
