_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 16/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 4 groups: vo | h | g | cn
                p_vo_h_g_cn=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 4 groups: vo | h | gc | n
                p_vo_h_gc_n=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vo | h | gn | c
                p_vo_h_gn_c=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 4 groups: vo | hc | g | n
                p_vo_hc_g_n=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19],  # ground
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vo | hg | c | n
                p_vo_hg_c_n=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 9, 10, 11, 19],  # human+ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
                # 4 groups: vo | hn | g | c
                p_vo_hn_g_c=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 20, 21, 22],  # human+nature
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                ],
                # 5 groups: v | h | g | c | no
                p_v_h_g_c_no=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22, 7, 8, 18, 23],  # nature+object
                ],
                # 5 groups: v | h | g | cn | o
                p_v_h_g_cn_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | h | g | co | n
                p_v_h_g_co_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19],  # ground
                    [12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # construction+object
                    [20, 21, 22],  # nature
                ],
                # 5 groups: v | h | gc | n | o
                p_v_h_gc_n_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                    [20, 21, 22],  # nature
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | h | gn | c | o
                p_v_h_gn_c_o=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                    [12, 13, 14, 15, 16, 17],  # construction
                    [7, 8, 18, 23],  # object
                ],
                # 5 groups: v | h | go | c | n
                p_v_h_go_c_n=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                    [12, 13, 14, 15, 16, 17],  # construction
                    [20, 21, 22],  # nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
