_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch 3/17 on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {vehicle+human} | {ground+...+object}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
                # 2 groups: vhgo | cn
                p_vhgo_cn=[
                    [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 19, 7, 8, 18, 23],  # vehicle+human+ground+object
                    [12, 13, 14, 15, 16, 17, 20, 21, 22],  # construction+nature
                ],
                # 2 groups: vhn | gco
                p_vhn_gco=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22],  # vehicle+human+nature
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # ground+construction+object
                ],
                # 2 groups: vhno | gc
                p_vhno_gc=[
                    [0, 1, 2, 3, 4, 5, 6, 20, 21, 22, 7, 8, 18, 23],  # vehicle+human+nature+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # ground+construction
                ],
                # 2 groups: vho | gcn
                p_vho_gcn=[
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 23],  # vehicle+human+object
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # ground+construction+nature
                ],
                # 2 groups: vn | hgco
                p_vn_hgco=[
                    [0, 1, 2, 3, 4, 20, 21, 22],  # vehicle+nature
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+ground+construction+object
                ],
                # 2 groups: vno | hgc
                p_vno_hgc=[
                    [0, 1, 2, 3, 4, 20, 21, 22, 7, 8, 18, 23],  # vehicle+nature+object
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17],  # human+ground+construction
                ],
                # 2 groups: vo | hgcn
                p_vo_hgcn=[
                    [0, 1, 2, 3, 4, 7, 8, 18, 23],  # vehicle+object
                    [5, 6, 9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+ground+construction+nature
                ],
                # 3 groups: v | h | gcno
                p_v_h_gcno=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6],  # human
                    [9, 10, 11, 19, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # ground+construction+nature+object
                ],
                # 3 groups: v | hc | gno
                p_v_hc_gno=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17],  # human+construction
                    [9, 10, 11, 19, 20, 21, 22, 7, 8, 18, 23],  # ground+nature+object
                ],
                # 3 groups: v | hcn | go
                p_v_hcn_go=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22],  # human+construction+nature
                    [9, 10, 11, 19, 7, 8, 18, 23],  # ground+object
                ],
                # 3 groups: v | hcno | g
                p_v_hcno_g=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17, 20, 21, 22, 7, 8, 18, 23],  # human+construction+nature+object
                    [9, 10, 11, 19],  # ground
                ],
                # 3 groups: v | hco | gn
                p_v_hco_gn=[
                    [0, 1, 2, 3, 4],  # vehicle
                    [5, 6, 12, 13, 14, 15, 16, 17, 7, 8, 18, 23],  # human+construction+object
                    [9, 10, 11, 19, 20, 21, 22],  # ground+nature
                ],
            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
