#!/usr/bin/env python
"""Generate the DSO hierarchy-ablation configs (Cetran-only split).

Starting from the six-group DSO hierarchy (vehicle v, human h, ground g,
construction c, nature n, object o) every set partition of the six groups
is scored: all 203 partitions (Bell number B(6); by number of groups
1 / 31 / 90 / 65 / 15 / 1) minus the single-group one, i.e. 202
hierarchies with 2..6 groups. Each is named ``p_<block>_<block>...`` with
the blocks written as group initials in canonical order (e.g. ``p_vh_gcno``
= {vehicle+human} | {ground+construction+nature+object}); the 6-block
partition ``p_v_h_g_c_n_o`` is the current hierarchy itself and doubles as
a consistency check. One extra hierarchy, ``sp``, halves every base group at
random (numpy RandomState(0) draw of 2026-08-24, kept literal here).

Each hierarchy adds ten score columns (group_* / gn_*) per point; the
evaluator keeps every column in RAM, so the variants are split into batches
of ``--batch-size`` hierarchies, one config per batch:

    configs/p3former/hier/p3former_2xb1_3x_dso_ood_hier_b<i>.py

Run from the repo root:
    python tools/make_dso_hierarchy_variants.py            # 203 hierarchies, 17 batches of 12
    for i in $(seq 1 17); do CUDA_VISIBLE_DEVICES=1 python test.py \\
        configs/p3former/hier/p3former_2xb1_3x_dso_ood_hier_b$i.py \\
        work_dirs/p3former_2xb1_3x_dso/epoch_36.pth \\
        --work-dir work_dirs/p3former_2xb1_3x_dso_ood_hier/b$i; done
then summarise the logs with tools/summarize_hierarchy_ablation.py.
"""
import argparse
import os
from collections import OrderedDict

GROUPS = OrderedDict([
    ('v', ('vehicle', [0, 1, 2, 3, 4])),
    ('h', ('human', [5, 6])),
    ('g', ('ground', [9, 10, 11, 19])),
    ('c', ('construction', [12, 13, 14, 15, 16, 17])),
    ('n', ('nature', [20, 21, 22])),
    ('o', ('object', [7, 8, 18, 23])),
])

# Stirling numbers of the second kind S(6, k), k = 1..6: the expected number
# of partitions with k blocks (they sum to the Bell number 203).
STIRLING_6 = {1: 1, 2: 31, 3: 90, 4: 65, 5: 15, 6: 1}

# numpy RandomState(0) draws of 2026-08-24 (see docstring).
SPLIT = [
    ('vehicle-a', [2, 3]), ('vehicle-b', [0, 1, 4]),
    ('human-a', [6]), ('human-b', [5]),
    ('ground-a', [9, 11]), ('ground-b', [10, 19]),
    ('construction-a', [13, 16, 17]), ('construction-b', [12, 14, 15]),
    ('nature-a', [20]), ('nature-b', [21, 22]),
    ('object-a', [7, 8]), ('object-b', [18, 23]),
]

HEADER = '''_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch {batch}/{num_batches} on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# p_vh_gcno_group_msp = {{vehicle+human}} | {{ground+...+object}}). Group
# initials: v vehicle, h human, g ground, c construction, n nature,
# o object. The PQ evaluator is dropped (panoptic quality does not depend
# on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
'''

FOOTER = '''            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
'''


def set_partitions(items):
    """Yield every set partition of ``items`` as a list of blocks."""
    if not items:
        yield []
        return
    first, rest = items[0], items[1:]
    for smaller in set_partitions(rest):
        yield [[first]] + smaller  # first in a block of its own
        for i in range(len(smaller)):  # or joined to an existing block
            yield smaller[:i] + [[first] + smaller[i]] + smaller[i + 1:]


def canonical(blocks):
    """Blocks as initial-strings: initials in GROUPS order inside a block,
    blocks ordered by their first initial (group order does not matter)."""
    order = {initial: i for i, initial in enumerate(GROUPS)}
    blocks = [''.join(sorted(block, key=order.get)) for block in blocks]
    return sorted(blocks, key=lambda block: order[block[0]])


def partition_variant(blocks):
    """(name, description, [(label, ids), ...]) for canonical ``blocks``."""
    groups = [('+'.join(GROUPS[i][0] for i in block),
               sum((GROUPS[i][1] for i in block), [])) for block in blocks]
    desc = f'{len(blocks)} groups: ' + ' | '.join(blocks)
    if len(blocks) == len(GROUPS):
        desc += ' (= current hierarchy)'
    return 'p_' + '_'.join(blocks), desc, groups


def partition_variants():
    """All partitions with 2..6 blocks, ordered by block count; counts are
    checked against the Stirling numbers (203 partitions in total)."""
    by_count = {k: [] for k in STIRLING_6}
    seen = set()
    for blocks in set_partitions(list(GROUPS)):
        blocks = tuple(canonical(blocks))
        if blocks in seen:
            raise RuntimeError(f'duplicate partition {blocks}')
        seen.add(blocks)
        by_count[len(blocks)].append(blocks)
    for k, expected in STIRLING_6.items():
        if len(by_count[k]) != expected:
            raise RuntimeError(f'{len(by_count[k])} partitions with {k} '
                               f'blocks, expected {expected}')
    variants = OrderedDict()
    for k in sorted(by_count):
        if k == 1:
            continue  # the single-group partition carries no information
        for blocks in sorted(by_count[k]):
            name, desc, groups = partition_variant(list(blocks))
            variants[name] = (desc, groups)
    return variants


def build_variants():
    """All partitions (2..6 blocks) followed by the split hierarchy."""
    variants = partition_variants()
    variants['sp'] = ('split each group in half', SPLIT)
    return variants


def render(batch, num_batches, variants):
    lines = [HEADER.format(batch=batch, num_batches=num_batches)]
    for name, (desc, groups) in variants.items():
        lines.append(f'                # {desc}\n')
        lines.append(f'                {name}=[\n')
        for label, ids in groups:
            lines.append(f'                    {ids},  # {label}\n')
        lines.append('                ],\n')
    lines.append(FOOTER)
    return ''.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--batch-size', type=int, default=12,
                    help='hierarchies per config (RAM: ~11 GB per hierarchy '
                    'on the 0.26B-point Cetran split)')
    ap.add_argument('--out-dir', default='configs/p3former/hier')
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    variants = build_variants()
    names = list(variants)
    batches = [names[i:i + args.batch_size]
               for i in range(0, len(names), args.batch_size)]
    for b, batch_names in enumerate(batches, start=1):
        path = os.path.join(args.out_dir,
                            f'p3former_2xb1_3x_dso_ood_hier_b{b}.py')
        subset = OrderedDict((n, variants[n]) for n in batch_names)
        with open(path, 'w') as fh:
            fh.write(render(b, len(batches), subset))
        print(f'{path}: {", ".join(batch_names)}')
    print(f'{len(names)} hierarchies in {len(batches)} batches')


if __name__ == '__main__':
    main()
