#!/usr/bin/env python
"""Generate the DSO hierarchy-ablation configs (Cetran-only split).

Starting from the six-group DSO hierarchy (vehicle v, human h, ground g,
construction c, nature n, object o) every hierarchy obtained by merging K of
the six groups into one (K = 2..5, all C(6, K) combinations: 15 + 20 + 15 +
6 = 56) is scored, plus one random halving of every group (``sp``, the
numpy RandomState(0) draw of 2026-08-24, kept literal here for
reproducibility).

Each hierarchy adds ten score columns (group_* / gn_*) per point; the
evaluator keeps every column in RAM, so the variants are split into batches
of ``--batch-size`` hierarchies, one config per batch:

    configs/p3former/hier/p3former_2xb1_3x_dso_ood_hier_b<i>.py

Run from the repo root:
    python tools/make_dso_hierarchy_variants.py
    for i in 1 2 3 4 5; do CUDA_VISIBLE_DEVICES=1 python test.py \\
        configs/p3former/hier/p3former_2xb1_3x_dso_ood_hier_b$i.py \\
        work_dirs/p3former_2xb1_3x_dso/epoch_36.pth \\
        --work-dir work_dirs/p3former_2xb1_3x_dso_ood_hier/b$i; done
then summarise the logs with tools/summarize_hierarchy_ablation.py.
"""
import argparse
import itertools
import os
from collections import OrderedDict

GROUPS = OrderedDict([
    ('v', ('vehicle', [0, 1, 2, 3, 4])),
    ('h', ('human', [5, 6])),
    ('g', ('ground', [9, 10, 11, 19])),
    ('c', ('construction', [12, 13, 14, 15, 16, 17])),
    ('n', ('nature', [20, 21, 22])),
    ('o', ('object', [7, 8, 18, 23])),
])

# numpy RandomState(0) draws of 2026-08-24 (see docstring).
SPLIT = [
    ('vehicle-a', [2, 3]), ('vehicle-b', [0, 1, 4]),
    ('human-a', [6]), ('human-b', [5]),
    ('ground-a', [9, 11]), ('ground-b', [10, 19]),
    ('construction-a', [13, 16, 17]), ('construction-b', [12, 14, 15]),
    ('nature-a', [20]), ('nature-b', [21, 22]),
    ('object-a', [7, 8]), ('object-b', [18, 23]),
]

HEADER = '''_base_ = ['../p3former_2xb1_3x_dso_ood.py']

# GENERATED by tools/make_dso_hierarchy_variants.py -- do not edit by hand.
# Hierarchy ablation batch {batch}/{num_batches} on the Cetran-only split:
# the hierarchies below are scored in the same inference pass as the
# current six-group hierarchy (keys prefixed with the variant name, e.g.
# m2_go_group_msp = ground+object merged). Group initials: v vehicle,
# h human, g ground, c construction, n nature, o object. The PQ evaluator
# is dropped (panoptic quality does not depend on the hierarchy).
model = dict(
    decode_head=dict(
        ood_cfg=dict(
            class_groups_variants=dict(
'''

FOOTER = '''            ))))

test_dataloader = dict(
    dataset=dict(dataset=dict(ann_file='dso_infos_cetran.pkl')))
val_dataloader = test_dataloader

val_evaluator = [
    dict(
        type='_OODPointMetric',
        ood_raw_ids=[17, 28],
        seg_offset=2**16,
        ignore_index=24),
]
test_evaluator = val_evaluator
'''


def build_variants():
    """Return OrderedDict name -> (description, [(group label, ids), ...])."""
    variants = OrderedDict()
    initials = list(GROUPS)
    for k in (2, 3, 4, 5):
        for combo in itertools.combinations(initials, k):
            merged = sum((GROUPS[i][1] for i in combo), [])
            label = '+'.join(GROUPS[i][0] for i in combo)
            groups = [(label, merged)]
            groups += [GROUPS[i] for i in initials if i not in combo]
            variants[f'm{k}_{"".join(combo)}'] = (f'merge {k}: {label}',
                                                 groups)
    variants['sp'] = ('split each group in half', SPLIT)
    return variants


def render(batch, num_batches, variants):
    lines = [HEADER.format(batch=batch, num_batches=num_batches)]
    for name, (desc, groups) in variants.items():
        lines.append(f'                # {desc}\n')
        lines.append(f'                {name}=[\n')
        for label, ids in groups:
            lines.append(f'                    {ids},  # {label}\n')
        lines.append('                ],\n')
    lines.append(FOOTER)
    return ''.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--batch-size', type=int, default=12,
                    help='hierarchies per config (RAM: ~11 GB per hierarchy '
                    'on the 0.26B-point Cetran split)')
    ap.add_argument('--out-dir', default='configs/p3former/hier')
    args = ap.parse_args()

    variants = build_variants()
    names = list(variants)
    batches = [names[i:i + args.batch_size]
               for i in range(0, len(names), args.batch_size)]
    os.makedirs(args.out_dir, exist_ok=True)
    for b, batch_names in enumerate(batches, start=1):
        path = os.path.join(args.out_dir,
                            f'p3former_2xb1_3x_dso_ood_hier_b{b}.py')
        subset = OrderedDict((n, variants[n]) for n in batch_names)
        with open(path, 'w') as fh:
            fh.write(render(b, len(batches), subset))
        print(f'{path}: {", ".join(batch_names)}')
    print(f'{len(names)} hierarchies in {len(batches)} batches')


if __name__ == '__main__':
    main()
